console.log ("this is my first javascript log")

console.log (document.querySelector('.greeting'))

let greetingDiv = document.querySelector('.greeting')

greetingDiv.textContent = 'Welcome to my page! This message was  generated by my JavaScript code!'